### PR TITLE
Add pack privacy switch

### LINKED ISSUE #8: Toggle pack privacy
- A toggle switch needs to be added for switching between public/private
- This boolean exists on the pack object
- A backend update may be required

### PR DESCRIPTION
**Pull request by darinalleman**
Closes #8 

Add a switch on the pack edit view for users to make their pack public or private. 
Because all packs created so far have the default value of `public: false` in the database but packs are actually public no matter the value, after merging this PR I recommend running the following command in the database so that all existing packs are public.

`UPDATE packs SET public=true;`

If you'd like me to add a sequelize migration, I can certainly do it, I just wasn't sure what kind of workflow exists for how the production database is managed by code. 

image
image

Here's a short clip that demonstrates that the user who is the owner of the pack can view their own pack whether or not it's private, but other users (including both users that are not logged in and users that are logged in) cannot view when the pack is marked private.

https://user-images.githubusercontent.com/1940054/105613847-15aa7380-5d93-11eb-95e6-5872f7a7202e.mp4

The tooltip says "When public, the pack will be viewable by anyone with a link".

## EDIT:
Added an indicator to the owner of a pack when viewing their private pack. It now says `PACK URL (PRIVATE)` if the pack is private and just `PACK URL` when the pack is public. I think it makes sense there since most users would want to see that when they're about to copy the link to share with others. 
image

Also added a better error page instead of the vague notification and never-ending spinner:
image

Thanks for the feedback @Callisto13!

### CODE REVIEW

**Comment by darinalleman** [comment]
This will need to be updated after MR #41 is merged.

**Comment by Callisto13** [comment]
Really nice 🎉 !

What do you think about the UX for when a Pack is not public? To me the spinner+pop-up says "something accidentally went wrong", where I think want we want here is more of "something is deliberately not allowed/found"... if that makes sense? Maybe a static (read: less spinny) page with a 404 and message like "Either the pack does not exist or you do not have permission to see it", or just "Pack not found" to give less away. What do you think?

**Comment by Callisto13** [comment]
Also what do you think about adding a marker of some sort on the owner's view pack page?

**Comment by darinalleman** [comment]
Good point! That certainly makes more sense. 

I don't think there are any existing full page error status pages, but I can make one. I'll also add something to the owner's view pack page that indicates public/private. Thanks!

**Pull request merged**
